# Generated by Django 5.1.6 on 2025-02-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_riskassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='alcohol',
            new_name='alcohol_intake',
        ),
        migrations.RenameField(
            model_name='riskassessment',
            old_name='stress',
            new_name='blood_sugar',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='chest_pain_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='exercise_induced_angina',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='stress_level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
