# Generated by Django 5.1.6 on 2025-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_rename_alcohol_riskassessment_alcohol_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='alcohol_intake',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='blood_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='cholesterol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='diabetes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='family_history',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'female'), (1, 'male')], null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='heart_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='obesity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='smoking',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
