# Generated by Django 5.1.6 on 2025-03-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_remove_riskassessment_prediction_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(0, 'female'), (1, 'male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='alcohol_intake',
            field=models.PositiveIntegerField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='diabetes',
            field=models.PositiveIntegerField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='family_history',
            field=models.PositiveIntegerField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='gender',
            field=models.CharField(choices=[(0, 'female'), (1, 'male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='obesity',
            field=models.PositiveIntegerField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='smoking',
            field=models.PositiveIntegerField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
    ]
