# Generated by Django 5.1.6 on 2025-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='exeercise_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'female'), (1, 'male')], null=True),
        ),
    ]
