# Generated by Django 5.1.6 on 2025-03-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_riskassessment_exeercise_hours_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='exeercise_hours',
            new_name='exercise_hours',
        ),
    ]
