# Generated by Django 5.1.6 on 2025-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_rename_exeercise_hours_riskassessment_exercise_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='blood_sugar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='chest_pain_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='exercise_induced_angina',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='stress_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
