# Generated by Django 5.1.6 on 2025-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_alter_riskassessment_blood_sugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='chest_pain_type',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'non-anginal pain'), (2, 'atypical angina'), (3, 'typical angina')], null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='exercise_induced_angina',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
    ]
